FROM node:20-alpine
WORKDIR /app
COPY package*.json . 
RUN npm install
COPY . .
EXPOSE 3000
RUN npm run build
CMD ["npm", "start"]



# FROM node:18-alpine

# WORKDIR /app

# COPY package*.json ./

# RUN npm install

# COPY . .

# RUN npm run build

# CMD ["npm", "start"]

# EXPOSE 3000
